# Generated by Django 4.2.27 on 2026-02-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobada"),
                            ("rejected", "Rechazada"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Mensaje opcional del solicitante"
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Notas del administrador"),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="clubs")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_private",
                    models.BooleanField(
                        default=True,
                        help_text="Si es True, unirse requiere aprobación por un Admin.",
                    ),
                ),
                (
                    "stripe_account_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Connect Express Account ID del dueño del club",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "stripe_account_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("active", "Activo"),
                            ("restricted", "Restringido"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cuota mensual en EUR (0 = gratis)",
                        max_digits=8,
                    ),
                ),
                (
                    "annual_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cuota anual en EUR (0 = gratis)",
                        max_digits=8,
                    ),
                ),
                (
                    "membership_benefits",
                    models.TextField(
                        blank=True,
                        help_text="Beneficios de la membresía, uno por línea",
                    ),
                ),
                (
                    "stripe_monthly_price_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Price ID para el plan mensual",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "stripe_annual_price_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Price ID para el plan anual",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClubMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobada"),
                            ("approved_pending_payment", "Aprobada (Falta Pago)"),
                            ("rejected", "Rechazada"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        choices=[
                            ("member", "Miembro Nuevo"),
                            ("loyal", "Asistente Fiel"),
                            ("founder", "Miembro Fundador"),
                            ("vip", "Socio VIP"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "events_attended",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de eventos del club a los que ha asistido para gamificación.",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Carta de presentación al solicitar unirse.",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClubPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("announcement", "📢 Anuncio"),
                            ("event_recap", "📸 Recap de evento"),
                            ("update", "📝 Actualización"),
                        ],
                        default="announcement",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="club_posts/"),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClubSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensual"),
                            ("annual", "Anual"),
                            ("free", "Gratuito"),
                        ],
                        default="free",
                        max_length=10,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("past_due", "Pago atrasado"),
                            ("canceled", "Cancelado"),
                            ("trialing", "Prueba"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClubWallPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("confirmed", "Confirmada"),
                            ("declined", "Rechazada"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confirmed_by_from", models.BooleanField(default=False)),
                ("confirmed_by_to", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DistributionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descripción del grupo"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo o imagen del grupo",
                        null=True,
                        upload_to="group_logos/",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Si es público, cualquiera puede unirse. Si es privado, requiere aprobación.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=300)),
                ("body", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
                ("error_text", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateTimeField()),
                ("location", models.CharField(max_length=200)),
                ("capacity", models.IntegerField()),
                (
                    "max_qr_codes",
                    models.IntegerField(
                        blank=True,
                        help_text="Límite de códigos QR/registros para este evento. Dejar en blanco para ilimitado.",
                        null=True,
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Si es True, las solicitudes de acceso requieren aprobación de un admin",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Si es True, el evento es visible para todos. Si es False, solo visible para miembros del grupo.",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Precio de entrada al evento. 0 = gratis",
                        max_digits=10,
                    ),
                ),
                (
                    "registration_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha límite para inscribirse. Dejar en blanco para ilimitado.",
                        null=True,
                    ),
                ),
                (
                    "stripe_account_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Account ID del organizador para Stripe Connect",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "platform_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Porcentaje de comisión que MUTUALS cobra por entrada vendida",
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Foto del evento", upload_to="event_photos/%Y/%m/"
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Ocultada por el organizador por incumplir normas.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("sad", "😞 Decepcionante"),
                            ("neutral", "😐 Normal"),
                            ("love", "😍 Increíble"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupAccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobada"),
                            ("rejected", "Rechazada"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Mensaje opcional del solicitante"
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Notas del administrador"),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("qr_code", models.ImageField(blank=True, upload_to="group_tokens")),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("usage_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="GroupInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "max_uses",
                    models.IntegerField(
                        blank=True,
                        help_text="Máximo número de usos. Null = ilimitado",
                        null=True,
                    ),
                ),
                ("use_count", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_code",
                    models.UUIDField(blank=True, default=None, null=True, unique=True),
                ),
                ("qr_code", models.ImageField(blank=True, upload_to="qrcodes")),
                ("used", models.BooleanField(default=False)),
                ("attendee_first_name", models.CharField(blank=True, max_length=100)),
                ("attendee_last_name", models.CharField(blank=True, max_length=100)),
                (
                    "attendee_type",
                    models.CharField(
                        choices=[
                            ("member", "Fallero"),
                            ("guest", "Invitado"),
                            ("child", "Niño"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        help_text="Nombre identificativo del QR (ej: Entrada VIP)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("attended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmado"),
                            ("declined", "Rechazado (No asistirá)"),
                            ("pending", "Pendiente"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "amount_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(max_length=200, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("paid", "Pagado"),
                            ("refunded", "Reembolsado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TicketTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Máximo de entradas disponibles a este precio"
                    ),
                ),
                ("sold", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Depósito"),
                            ("payment", "Pago"),
                            ("refund", "Reembolso"),
                            ("withdrawal", "Retiro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
