# Generated by Django 4.2.27 on 2026-02-28 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "max_uses",
                    models.IntegerField(
                        blank=True,
                        help_text="Máximo número de usos. Null = ilimitado",
                        null=True,
                    ),
                ),
                ("use_count", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="events.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="groupaccessrequest",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="groupaccessrequest",
            name="group",
        ),
        migrations.RemoveField(
            model_name="groupaccessrequest",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="groupaccessrequest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="groupaccesstoken",
            name="group",
        ),
        migrations.RemoveField(
            model_name="groupaccesstoken",
            name="user",
        ),
        migrations.RemoveField(
            model_name="groupinvitation",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="groupinvitation",
            name="group",
        ),
        migrations.RemoveField(
            model_name="event",
            name="group",
        ),
        migrations.DeleteModel(
            name="DistributionGroup",
        ),
        migrations.DeleteModel(
            name="GroupAccessRequest",
        ),
        migrations.DeleteModel(
            name="GroupAccessToken",
        ),
        migrations.DeleteModel(
            name="GroupInvitation",
        ),
    ]
