# Generated by Django 4.2.27 on 2026-03-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("events", "0004_clubaccesstoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Intereses/temáticas del club para el Radar de descubrimiento",
                related_name="clubs",
                to="users.interesttag",
            ),
        ),
    ]
