# Generated by Django 4.2.27 on 2026-03-01 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_club_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubwallpost",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="events.clubwallpost",
            ),
        ),
    ]
