# Generated by Django 4.2.27 on 2026-03-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_clubwallpost_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubwallpost",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="club_wall_images/"
            ),
        ),
    ]
