# Generated by Django 4.2.27 on 2026-03-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_clubwallpost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubwallpost",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
