# Generated by Django 6.0 on 2026-01-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_registration_alias_registration_attended_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmado"),
                    ("declined", "Rechazado (No asistirá)"),
                    ("pending", "Pendiente"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
    ]
