# Generated by Django 6.0 on 2026-01-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_eventdecline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="entry_code",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="EventDecline",
        ),
    ]
