# Generated by Django 6.0 on 2026-01-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0023_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="event",
            name="event_public_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="registration",
            name="reg_event_user_idx",
        ),
        migrations.RemoveIndex(
            model_name="registration",
            name="reg_entry_code_idx",
        ),
        migrations.RemoveIndex(
            model_name="registration",
            name="reg_used_idx",
        ),
        migrations.AlterField(
            model_name="registration",
            name="entry_code",
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
