# Generated by Django for performance optimization
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_wallet_transaction'),  # Adjust to your latest migration
    ]

    operations = [
        # Index for Registration lookups by event + user (most common query)
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'user'], name='reg_event_user_idx'),
        ),
        # Index for QR code lookups (scanning)
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['entry_code'], name='reg_entry_code_idx'),
        ),
        # Index for Event listing by public + date
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_public', 'date'], name='event_public_date_idx'),
        ),
        # Index for Registration attendance status
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['used'], name='reg_used_idx'),
        ),
    ]
