# Generated by Django 6.0 on 2026-01-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0024_nullable_entry_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="entry_code",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
