# Generated by Django 6.0 on 2026-02-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_force_entry_code_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="entry_code",
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
