# Generated by Django 6.0 on 2026-02-08 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0027_alter_registration_entry_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attendee_first_name", "")),
                fields=("user", "event"),
                name="unique_personal_registration",
            ),
        ),
    ]
