# Generated by Django 4.2.27 on 2026-02-24 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("match", "🌐 Match de Networking"),
                            ("connection_request", "🤝 Solicitud de Conexión"),
                            ("wave", "👋 Saludo recibido"),
                            ("memories_unlocked", "📸 Muro desbloqueado"),
                            ("event_reminder", "📅 Recordatorio de evento"),
                            ("system", "⚙️ Sistema"),
                        ],
                        default="system",
                        max_length=30,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "data_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra payload for routing on frontend",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "📢 Spam o contenido repetitivo"),
                            ("inappropriate", "🔞 Contenido inapropiado"),
                            ("harassment", "😡 Acoso o comportamiento abusivo"),
                            ("fake", "🎭 Perfil falso o suplantación"),
                            ("other", "⚠️ Otro motivo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente revisión"),
                            ("reviewed", "Revisado — sin acción"),
                            ("actioned", "Revisado — acción tomada"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
