# Generated by Django 6.0 on 2026-02-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_id_alter_verificationcode_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationcode",
            name="user",
        ),
        migrations.AlterField(
            model_name="verificationcode",
            name="verification_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("phone", "Teléfono"),
                    ("password_reset", "Restablecer Contraseña"),
                ],
                max_length=20,
            ),
        ),
    ]
